###
## This file is generated basing on production.yml file. Please only edit the templates.
###

##ยง '\n' + fs.readFileSync(__dirname + "/production.yml", "UTF-8").replace(/^\s*## production_only\n((^(?!(\s*## end_production_only))[^\n]*\n)+)\s*## end_production_only\n/gmiu, "").split(sectionSign()).join("_embedded_template_disabled_") + '\n' ยง##
###
## Production_only and end_production_only are used to properly generate docker-compose.yml file.
###


version: "3"

services:
  #_embedded_template_disabled_ data.config.sql.docker.services.db.name + ':'
  wise_sql_db:
    image: postgres:10-alpine
    #_embedded_template_disabled_ 'container_name: ' + data.config.sql.docker.services.db.container
    container_name: wise_sql_db
    expose: # expose exposes ports only inside this stack and do not publish them to host machine.
      - "5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./sql:/docker-entrypoint-initdb.d:ro"
      - "pgdata:/var/lib/postgresql/data" #_embedded_template_disabled_< '- "' + data.config.sql.docker.volumes.db.name + ':/var/lib/postgresql/data"'
    restart: always

  #_embedded_template_disabled_ data.config.sql.docker.services.pusher.name + ':'
  wise_sql_pusher:
    build: ./pusher
    image: wise/sql-pusher #_embedded_template_disabled_< 'image: ' + data.config.sql.docker.services.pusher.image
    container_name: wise-sql-pusher #_embedded_template_disabled_< 'container_name: ' + data.config.sql.docker.services.pusher.container
    command: ./wait-for wise_sql_db:5432 -- npm start #_embedded_template_disabled_< 'command: ./wait-for ' + data.config.sql.docker.services.db.name + ':5432 -- npm start'
    depends_on:
      - "wise_sql_db" #_embedded_template_disabled_< '- "' + data.config.sql.docker.services.db.name + '"'
    networks:
      - default
    environment:
      #_embedded_template_disabled_ 'DATABASE_URL: postgres://pusher:pusher@' + data.config.sql.docker.services.db.name + ':5432/app_db'
      DATABASE_URL: postgres://pusher:pusher@wise_sql_db:5432/app_db
      #_embedded_template_disabled_ "STEEM_API_URL: \"" + data.config.steem.apis.filter(api => api.get_block === true).map(api => api.url).join(",") + "\""
      STEEM_API_URL: "https://api.steemit.com,https://rpc.buildteam.io"
      # START_BLOCK_NUM: 25021220 # interesting moment for testing
      WISE_LOG_LEVEL: info
    restart: always

  #_embedded_template_disabled_ data.config.sql.docker.services.postgrest.name + ':'
  postgrest:
    image: postgrest/postgrest
    #_embedded_template_disabled_ 'container_name: ' + data.config.sql.docker.services.postgrest.container
    container_name: wise-sql-postgrest
    command: bash -c "echo \"Waiting 12s...\" && sleep 12 && echo \"Starting postgrest\" && exec postgrest /etc/postgrest.conf"
    expose:
      - 3000
    depends_on:
      #_embedded_template_disabled_ '- "' + data.config.sql.docker.services.db.name + '"'
      - "wise_sql_db"
      #_embedded_template_disabled_ '- "' + data.config.sql.docker.services.pusher.name + '"'
      - "wise_sql_pusher"
    networks:
      - default
    environment:
      #_embedded_template_disabled_ "PGRST_SERVER_PROXY_URI: " + data.config.sql.url.production
      PGRST_SERVER_PROXY_URI: https://sql.wise.vote/
      #_embedded_template_disabled_ 'PGRST_DB_URI: postgres://postgrest:postgrest@' + data.config.sql.docker.services.db.name + ':5432/app_db'
      PGRST_DB_URI: postgres://postgrest:postgrest@wise_sql_db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgrest_anon
      PGRST_MAX_ROWS: 1000 #_embedded_template_disabled_< 'PGRST_MAX_ROWS: ' + d(data.config.sql.protocol.maxRowsPerPage)
    volumes:
      - "./postgrest:/postgrest_service:ro"
    restart: always

  #_embedded_template_disabled_ data.config.sql.docker.services.api_proxy.name + ':'
  wise_sql_api_proxy:
    image: nginx
    #_embedded_template_disabled_ 'container_name: ' + data.config.sql.docker.services.api_proxy.container
    container_name: wise_sql_api_proxy
    command: bash -c "sleep 15 && exec nginx -g 'daemon off;'"
    ports:
      - 1080:80
    networks:
      - default
    volumes:
      - ./api_proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./api_proxy/html/:/usr/share/nginx/html/:ro
    restart: always

volumes:
  pgdata: # steem-wise-sql_pgdata

##ยง ยง.##
