version: "3"
services:
  db:
    image: postgres:10-alpine
    expose: # expose exposes ports only inside this stack and do not publish them to host machine.
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./sql:/docker-entrypoint-initdb.d:ro"
      - "steem_wise_sql_pgdata:/var/lib/postgresql/data"
  
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    environment:
      PGRST_DB_URI: postgres://postgrest:postgrest@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgrest_anon
      PGRST_MAX_ROWS: 1000

#  adminer: # for debugging
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  pusher:
    build: ./pusher
    depends_on:
      - "db"
    environment:
      DATABASE_URL: postgres://pusher:pusher@db:5432/app_db
      STEEM_API_URL: https://api.steemit.com/
      # START_BLOCK_NUM: 25021220 # interesting moment for testing

volumes:
  steem_wise_sql_pgdata: