version: "3"

services:
  #§ data.config.sql.docker.services.db.name + ':'
  wise_sql_db:
    restart: always

  #§ data.config.sql.docker.services.pusher.name + ':'
  wise_sql_pusher:
    restart: always

  #§ data.config.sql.docker.services.postgrest.name + ':'
  postgrest:
    environment:
      #§ "PGRST_SERVER_PROXY_URI: " + data.config.sql.url.staging
      PGRST_SERVER_PROXY_URI: https://sql.dev.wise.vote/
    restart: always

  #§ data.config.sql.docker.services.api_proxy.name + ':'
  wise_sql_api_proxy:
    restart: always
