version: "3"
services:
  db:
    image: postgres:10-alpine
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./db-init:/docker-entrypoint-initdb.d:ro"
  
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    depends_on:
      - "db"
    environment:
      PGRST_DB_URI: postgres://postgrest:postgrest@db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgrest_anon
      PGRST_MAX_ROWS: 1000

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pusher:
    build: ./pusher
    depends_on:
      - "db"
    environment:
      DATABASE_URL: postgres://pusher:pusher@db:5432/app_db
      STEEM_API_URL: https://api.steemit.com/