version: "3"

networks:
  proxy-tier:
    external:
      name: caddy-proxy
  default:
    driver: bridge

services:
  wise_sql_db:
    image: postgres:10-alpine
    container_name: wise_sql_db
    expose: # expose exposes ports only inside this stack and do not publish them to host machine.
      - "5432"
    networks:
      - default
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./sql:/docker-entrypoint-initdb.d:ro"
      - "pgdata:/var/lib/postgresql/data"
  
#  adminer: # for debugging
#    image: adminer
#    restart: always
#    ports:
#      - 3002:3002

  wise_sql_pusher:
    build: ./pusher
    command: ./wait-for wise_sql_db:5432 -- npm start
    depends_on:
      - "wise_sql_db"
    networks:
      - default
    environment:
      DATABASE_URL: postgres://pusher:pusher@wise_sql_db:5432/app_db
      #§ "STEEM_API_URL: \"" + data.config.steem.apis.filter(api => api.get_block === true).map(api => api.url).join(",") + "\""
      STEEM_API_URL: "https://api.steemit.com,https://steemd.minnowsupportproject.org,https://rpc.buildteam.io,https://rpc.steemliberator.com,https://steemd.privex.io"
      # START_BLOCK_NUM: 25021220 # interesting moment for testing
      LOG_LEVEL: info

  postgrest:
    image: postgrest/postgrest
    command: bash -c "echo \"Waiting 12s...\" && sleep 12 && echo \"Starting postgrest\" && exec postgrest /etc/postgrest.conf"
    expose:
      - 3000
    depends_on:
      - "wise_sql_db"
      - "wise_sql_pusher"
    networks:
      - proxy-tier
      - default
    environment:
      # https://github.com/PostgREST/postgrest/blob/f6c1ff810e92321f2cd522058d5c6fd74cb64226/docker/postgrest.conf
      #§ "PGRST_SERVER_PROXY_URI: " + data.config.sql.endpoint.schema + "://" + data.config.sql.endpoint.host + "/"
      PGRST_SERVER_PROXY_URI: https://sql.wise.vote/
      PGRST_DB_URI: postgres://postgrest:postgrest@wise_sql_db:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: postgrest_anon
      PGRST_MAX_ROWS: 1000
      #§ "VIRTUAL_HOST: \"" + data.config.sql.endpoint.host + "\""
      VIRTUAL_HOST: "sql.wise.vote"
      VIRTUAL_NETWORK: "caddy-proxy"
      VIRTUAL_PORT: 3000
      #§ 'CADDY_TLS: ' + ( data.config.sql.endpoint.schema === "https" ? '"yes"' : '"no"')
      CADDY_TLS: "yes"
      CADDY_TIMEOUTS: "read 5m, write 2m"
    volumes:
      - "./postgrest:/postgrest_service:ro"

  #wise_sql_swagger_host:
  #  image: nginx
  #  volumes:
  #    - ./api_specification:/usr/share/nginx/html:ro
  #  networks:
  #    - proxy-tier
  #  environment:
  ##§ "#    VIRTUAL_HOST: \"" + data.config.sql.endpoint.host + "\""
  #    VIRTUAL_HOST: "sql.wise.vote"
  #    VIRTUAL_NETWORK: "caddy-proxy"
  #    VIRTUAL_PORT: 80
  #§ '#    CADDY_TLS: ' + ( data.config.sql.endpoint.schema === "https" ? '"yes"' : '"no"')
  #    CADDY_TLS: "yes"
  #    CADDY_TIMEOUTS: "read 5m, write 2m"
  #  restart: always

volumes:
  pgdata: # steem-wise-sql_pgdata
